//PRACTICA N1
//var nome = window.prompt('coloque su nombre') //so preguntando el nombre...
window.alert('bienvenido a nuetro sitio web ' + nome + '!')//concatenacion...

//PRACTICA N2...
var n1 = Number(window.prompt('escriba un numero'))
var n2 = Number(window.prompt('escriba otro numero'))
var rs = n1 + n2